"""
Exterior noise estimation

Based on: https://www.sciencedirect.com/science/article/pii/B978012818465300015X#fo0065
And: https://dspace.mit.edu/bitstream/handle/1721.1/62320/712082963-MIT.pdf?sequence=2

@author: Sebastiaan, Thomas
"""

import numpy as np
from ambiance import Atmosphere


# Constants
g = 9.81
ka = 1.4
R = 287.15
T = 288.15
Intensity_ref = 10 ** (-12)
p_ref = 2 * 10 ** (-5) #[Pa]

###########################################################################################

# Take-off parameter values

# BWB
Np = 13
Fp = 155000
Vp = 298

# A320-type
N = 2
F = 200000
V = 110000


def dBDecrease(Np, Fp, Vp, N, F, V):
    """
    Function used to estimate the reduced noise in dB based on a few parameters.

    Input:
    ---------
    Np, number of engines of BWB
    Fp, thrust of BWB [N]
    Vp, effective exhaust velocity of BWB
    N, number of engines of conventional
    F, thrust of concentional [N]
    V, effective exhaust velocity of BWB

    Output:
    ---------
    dBL, reduced noise [dB]

    """

    # Decibel reductions (individual)
    dBLN = 10 * np.log10(Np / N)  # Number of engines
    dBLF = 10 * np.log10(Fp / F)  # Thrust
    dBLV = 10 * np.log10(Vp / V)  # Exhaust velocity

    # Total decibel reduction
    dBL = dBLN + dBLF + dBLV

    return dBL

def PNL_Engines(V_tip, gamma, R, T, HP, Nb, Dp, d, theta):
    """
    Function to estimate the perceived noise level due to the engines
    at a distance d from the aircraft

    Input:
    ---------
    V_tip, blade tip velocity [m/s]
    gamma, aerodynamic constant
    R, gas constant
    T, ambient air temperature [T]
    HP, horse power [hp]
    Nb, number of blades
    Dp, blade diameter [m]
    d, distance from observer [ft]
    theta, angle from observer [degrees]

    Output:
    ---------
    PNL, perceived noise level [dB]

    """

    # Calculate Tip Mach Number
    M_tip = V_tip / (np.sqrt(gamma * R * T))

    # Determination of Partial Level 1
    FL1 = 17.237 + (36.886 * M_tip) + (6.88 * np.log(HP))

    # Determination of Partial Level 2
    FL2 = 32.551 - (8.312 * np.log(Nb)) - (8.642 * np.log(Dp))

    # Determination of Partial Level 3
    if d < 100:
        FL3 = 16.29 - (0.5 * np.log(d))
    else:
        FL3 = 56 - (9.1202 * np.log(d))

    # Determine Directivity Correction
    DI = (4.4464 * (10 ** -11) * (theta ** 6)) - (2.1049 * (10 ** -8) * (theta ** 5)) + (
                3.56 * (10 ** -6) * (theta ** 4)) - (0.0002575 * (theta ** 3)) + (0.006073 * (theta ** 2)) + (
                     0.15363 * theta) - 8.1226

    # Number of Propellers Correction
    NC = 11  # Extrapolated

    # Overall Sound Pressure Level Determination (SPL)
    SPL = FL1 + FL2 + FL3 + DI + NC

    # Perceived Noise Level (PNL)
    s = (0.2 * Dp) - 1
    t = 2.25 - (2.5 * M_tip)
    PNL_n = 9.048 - (3.349 * s) - (3.335 * t) + (0.212 * s * t)
    PNL = SPL + PNL_n

    PNL_duct = PNL + Noise_shielding_factor

    return PNL_duct

def PNL_LandingGear(h, Theta, Phi, r, bw, M_inf, n_nlg, n_mlg, d_nlg, d_mlg, l_nlg, l_mlg):
    """
    Function to estimate the noise generated by the 
    nose and main landing gear

    Taken from:
    https://ntrs.nasa.gov/api/citations/19820012073/downloads/19820012073.pdf

    Inputs:
    -----
    h, altitude [m]
    Theta, longitudinal angle to observer, measured positive downwards from horizontal [deg]
    Phi, longitudinal angle to observer, measured positive downwards from horizontal [deg]
    r, distance from observer [ft]
    bw, wing span [m]
    M_inf, freestream Mach number [-]
    n_nlg, number of wheels per nose landing gear [-]
    n_mlg, number of wheels per main landing gear [-]
    d_nlg, tire diameter of nose landing gear [m]
    d_mlg, tire diamter of main lanidng gear [-]
    l_nlg, nose landing gear strut length [m]
    l_mlg, main landing gear strut length [m]

    Outputs:
    -----
    PNL_NLG, perceived noise level for the nose landing gear [dB]
    PNL_MLG, perceived noise level for the main landing gear [dB]
    """

    #Atmospheric properties
    atmos = Atmosphere(h)
    rho_inf = atmos.density
    a_inf = atmos.speed_of_sound

    #Constants from paper
    S_nlg = 10 ** 0.5 #[-], value corresponding to max value for F from fig.11
    S_nlgstrut = 10 ** 0.0 #[-], value corresponding to max value for F from fig.12
    S_mlg = 10 ** 0.5 #[-], value corresponding to max value for F from fig.13
    S_mlgstrut = 10 ** 0.0 #[-], value corresponding to max value for F from fig.14

    D_LG = 3/2 * (0.5 - 0.5 * np.cos(2 * np.radians(Theta)))
    D_Strut = 3 * (0.5 - 0.5 * np.cos(2 * np.radians(Theta))) * (0.5 - 0.5 * np.cos(2 * np.radians(Phi)))
    F_nlg = 13.59 * S_nlg ** 2 * (12.5 + S_nlg ** 2) ** (-2.25) 
    F_nlgstrut = 5.325 * S_nlgstrut ** 2 * (30 + S_nlgstrut ** 8) ** (-1)
    F_mlg = 0.0577 * S_mlg ** 2 * (1 + 0.25 * S_mlg ** 2) ** (-1.5)
    F_mlgstrut = 1.28 * S_mlgstrut ** 3 * (1.06 + S_mlgstrut **2) ** (-3)
    
    r = r * 0.3048 #convert distance back into meters
    rs = r / bw

    AcousticPowerNLG = (4.349 * 10 ** (-4)) * M_inf ** 6 * n_nlg * (d_nlg / bw) ** 2  
    AcousticPowerStrutNLG = (2.753 * 10 ** (-4)) * M_inf ** 6 * (d_nlg / bw) ** 2 * l_nlg / d_nlg
    AcousticPowerMLG = (3.414 * 10 ** (-4)) * M_inf ** 6 * n_mlg * (d_mlg / bw) ** 2  
    AcousticPowerStrutMLG = (2.753 * 10 ** (-4)) * M_inf ** 6 * (d_mlg / bw) ** 2 * l_mlg / d_mlg

    p2Star_NLG = AcousticPowerNLG / (4 * np.pi * rs ** 2) * D_LG * F_nlg / ((1 - M_inf * np.cos(Theta)) ** 4)
    p2Star_StrutNLG = AcousticPowerStrutNLG / (4 * np.pi * rs) ** 2 * D_Strut * F_nlgstrut / ((1 - M_inf * np.cos(Theta)) ** 4)
    p2Star_MLG = AcousticPowerMLG / (4 * np.pi * rs) ** 2 * D_LG * F_mlg / ((1 - M_inf * np.cos(Theta)) ** 4)
    p2Star_StrutMLG = AcousticPowerStrutMLG / (4 * np.pi * rs) ** 2 * D_Strut * F_mlgstrut / ((1 - M_inf * np.cos(Theta)) ** 4)

    NLGp2star = p2Star_NLG + p2Star_StrutNLG
    MLGp2star = 2 * (p2Star_MLG + p2Star_StrutMLG)

    PNL_NLG = 10 * np.log10(NLGp2star) + 20 * np.log10((rho_inf * a_inf ** 2) / p_ref) #[dB]
    PNL_MLG = 10 * np.log10(MLGp2star) + 20 * np.log10((rho_inf * a_inf ** 2) / p_ref) #[dB]

    return PNL_NLG, PNL_MLG

def PNL_wingtiplet(M_inf, a_tip, L_tip, r, Theta_e, phi_e):
    """
    Function to estimate the noise levels of the 
    wing tip or winglet

    Inputs:
    -----
    M_inf, freestream Mach number [-]
    a_tip, tip angle of attack relative to the freestream [deg]
    L_tip, turbulent wetted length of the edge [m]
    r, distance to observer [ft]
    Theta_e, longitudinal angle to observer, measured positive downwards from horizontal [deg]
    phi_e, longitudinal angle to observer, measured positive downwards from horizontal [deg]

    Outputs:
    -----
    PNL, sound pressure level of the wing tip / winglet
    """

    #Constants defined in the paper:
    St = 4 #[-], Approximation
    
    r = r * 0.3048 #convert r back into meters
    
    #Directivity function for low frequencies (more valid during high AoA)
    D = (0.5 - 0.5 * np.cos(2 * np.radians(Theta_e))) * (0.5 - 0.5 * np.cos(2 * np.radians(phi_e))) / (1 + M_inf * np.cos(np.radians(Theta_e))) ** 4
    PNL = 10 * np.log10((2 * M_inf ** 5 * (1 + 0.036 * np.radians(a_tip)) ** 3 * L_tip * D) / (r ** 2)) - 30.5 * (np.log10(St) + 0.3) ** 2 + 126 #[dB]
   
    return PNL

def AircraftNoise(V_tip, ka, R,T, HP, Nb, Dp, r, theta, h, phi, b, M_inf, n_nlg, n_mlg, d_nlg, d_mlg, l_nlg, l_mlg, a_tip, L_tip):
    """ Main function combining the different noise components and returning the overall aircraft noise"""
    PNL_ENG = PNL_Engines(V_tip, ka, R, T, HP, Nb, Dp, r, theta)
    PNL_NLG, PNL_MLG = PNL_LandingGear(h, theta, phi, r, b, M_inf, n_nlg, n_mlg, d_nlg, d_mlg, l_nlg, l_mlg)
    PNL_WLET = 0 #PNL_wingtiplet(M_inf, a_tip, L_tip, r, theta, phi)

    print("-----\n Aircraft Noise Analysis \n-----")
    print("Distance from aircraft:", r * 0.3048, "[m]")
    print("Theta:", theta, "[deg]")
    print("Phi:", phi, "[deg]")
    print("Altitude:", h, "[m]")

    print("\nEngine Noise:", PNL_ENG, "[dB]")
    print("Nose Landing gear:", PNL_NLG, "[dB]")
    print("Main Landing gear:", PNL_MLG, "[dB]")
    print("Wing tip & winglet noise:", PNL_WLET, "[dB]")

    PNL_Watts = 10 ** (PNL_ENG / 20) * p_ref + 10 ** (PNL_NLG / 20) * p_ref + 10 ** (PNL_MLG / 20) * p_ref + 10 ** (PNL_WLET / 20) * p_ref #[W/m2]
    PNL = 20 * np.log10(PNL_Watts / p_ref)
    print("-----")
    print("Aircraft noise:", PNL, "[dB]")
    return PNL

############################################################################################
#
#   TEST INPUTS
#
###########################################################################################

rpm = 2966.14  # rpm
V_tip = 259.52  # blade tip velocity
P = 0.766 * 10 ** 6  # power
HP = P * 0.00134102209  # horsepower
Nb = 8  # number of blades
Dp = 1.6710 * 3.28
r = 100.86 * 3.28  # distance of observer [ft]
theta = 90  # longitudinal angular position of observer [deg]
phi = 0 #lateral angular position of observer [deg]
Duct_factor = -17.25  # decrease in dB due to duct [dB]
Noise_shielding_factor = -20 #decrease due to fuselage noise shielding [dB]
b = 36 #[m]

#Code test input
PNL = AircraftNoise(V_tip, ka, R, T, HP, Nb, Dp, r, theta, 0, phi, b, 0.25, 2, 4, 1, 1, 3, 3, 0, 0)